"================
" Install plugins
"================

call plug#begin('~/.vim/plugged')

" General
Plug 'kien/ctrlp.vim'
Plug 'Valloric/YouCompleteMe'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'vim-airline/vim-airline'
Plug 'airblade/vim-gitgutter'
Plug 'wesQ3/vim-windowswap'
Plug 'terryma/vim-multiple-cursors'

" Languages
Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
Plug 'facebook/vim-flow', { 'for': 'javascript' }
Plug 'leafgarland/typescript-vim', { 'for': 'typescript' }

" Themes
Plug 'tomasr/molokai'

call plug#end()

"=========================
" Custom Commands/Settings
"=========================

" open splits to the left || below
set splitbelow
set splitright

" Highlight all search matches
set hlsearch

" enable mouse clicking/dragging
set mouse=a

" allow backspace to delete through line breaks
set backspace=indent,start

" disable swap files
set noswapfile

" enable persistent undo so that undo history persists across vim sessions
set undofile
set undodir=~/.vim/undo

" increase update frequency (recommended by vim-gitgutter)
set updatetime=250

" NERDTree
" show hidden files by default
let NERDTreeShowHidden=1

" ctrlp
let g:ctrlp_custom_ignore = {
  \ 'dir': '\v[\/](\.git|node_modules|\.sass-cache|bower_components|build)$'
  \ }

" vim-flow
let g:flow#enable = 0

"===================
" Custom Keymappings
"===================

" set leader key
let mapleader=','

" disable CTRL-w + q
nmap <C-w>q <NOP>
nmap <C-w><C-q> <NOP>

" open NERDTreeTabs with Leader + n
map <leader>n :NERDTreeTabsToggle<CR>

" reload ctrlp cache with Leader + p
map <leader>p :ClearCtrlPCache<CR>

" clear search highlight
nmap <silent> <leader>/ :nohlsearch<CR>

"========================
" Language/Style Settings
"========================

" General
syntax on
filetype plugin indent on
colorscheme molokai

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

set number

set colorcolumn=100
augroup LongLines
  autocmd!
  autocmd FileType * match none
  autocmd FileType python,c,sh,javascript,flow,jsx match Error '\%>100v.\+'
augroup END

" show whitespace
set list
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+

"=================
" Custom Functions
"=================

" DiffSaved: diff the current buffer with the contents on disk
function! s:DiffWithSaved()
  let filetype=&ft
  diffthis
  vnew | r # | normal! 1Gdd
  diffthis
  exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
com! DiffSaved call s:DiffWithSaved()
